name: Create Organization Repository

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      # # Step 1: Checkout the current repository
      # - name: Checkout repository
      #   uses: actions/checkout@v2

      # # Step 2: Set up Node.js environment
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run JavaScript script to create a repository
      - name: Run create-repo script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
        run: node scripts/create-repo.js
