name: List Organization Repository

on:
  workflow_dispatch: # Allows manual trigger of the workflow
    inputs:
      targetorg:
        description: "Target Organisation"
        required: true
        type: string

jobs:
  list-org-repo:
    runs-on: ubuntu-latest
    steps: 
      - name: Run script
        uses: actions/github-script@v6.4.0
        with: 
         github-token: ${{ secrets.Repo_PAT }}
         script: |
          
            const response = await github.request('GET /orgs/mt4621-org/repos', {
              org: `orgName`
            });
            console.log(response);
        
